name: Convert ODT to PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LibreOffice
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice

    - name: Convert ODT files to PDF
      run: |
        for file in $(find . -type f -name "*.odt"); do
          echo "Converting $file to PDF..."
          libreoffice --headless --convert-to pdf "$file" --outdir "$(dirname "$file")"
        done

    - name: Debug - List generated PDFs
      run: |
        echo "=== Liste de tous les fichiers PDF générés ==="
        find . -name "*.pdf" -type f
        echo ""
        echo "=== Contenu des dossiers UAA ==="
        for dir in UAA*; do
          if [ -d "$dir" ]; then
            echo "Contenu de $dir:"
            ls -la "$dir" || echo "Erreur lors de la lecture de $dir"
            echo ""
          fi
        done

    - name: Commit and push generated PDFs
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        
        # Méthode plus robuste : ajouter tous les PDF trouvés dans les dossiers UAA
        echo "=== Ajout des fichiers PDF avec find ==="
        find . -path "./UAA*/*.pdf" -exec git add {} \;
        
        # Vérifier ce qui a été ajouté
        echo ""
        echo "=== Fichiers ajoutés à Git ==="
        git status --porcelain
        echo ""
        echo "=== Statut détaillé ==="
        git status
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git commit -m "Automated ODT to PDF conversion [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
