name: Convert ODT to PDF

on:
  push:
    paths:
      - 'UAA12/*.odt'      # Ou dans un sous-dossier
  workflow_dispatch:      # Permet de lancer manuellement

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LibreOffice (headless)
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice

    - name: Convert ODT to PDF
      run: |
        for file in $(find . -name "*.odt"); do
          libreoffice --headless --convert-to pdf "$file" --outdir "$(dirname "$file")"
        done

    - name: Commit and push generated PDFs
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add *.pdf UAA12/*.pdf
        git commit -m "Automated ODT to PDF conversion"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
